# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 愛吃東西的RD
subtitle: Node.js、JavaScript、好書筆記、吃吃喝喝
description: Node.js、JavaScript、好書筆記、吃吃喝喝
author: AndrewChen
language: zh-TW
email: chenpoanandrew@gmail.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.andrewchen.tw/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categoriesl
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: ture # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: icarus

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/PolarBearAndrew/blog
  branch: gh-pages
  message:

sitemap:
  path: sitemap.xml

# themes ------
# Header
# menu:
#   Home: .
#   Archives: archives
#   Categories: categories
#   Tags: tags
#   About: about

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# widgets:
# - recent_posts
# - category
# - archive
# - tag
# - tagcloud
# - links

# # Links
# links:
  # JSDC: http://jsdc.tw
  # Hackathon Taiwan: https://hackathon.tw
  # hexo: http://hexo.iov
  # theme: https://github.com/ppoffice/hexo-theme-hueman

# Miscellaneous
# google_analytics: UA-65872031-1
# favicon: /images/logo.png

html_minifier:
  enable: true
  ignore_error: false
  exclude:

css_minifier:
  enable: true
  exclude: 
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false