# Menus
menu:
    首頁: .
    文章時間軸: archives
    分類檢索: categories
    # 標籤檢索: tags
    關於我: about


# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: /images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: /images/me.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: AndrewChen
        author_title: Node.js Backend Developer
        location: Taipei, Taiwan
        follow: /about
    # highlight: agate
    # highlight: hybrid
    highlight: github

    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: /images/favicon.png
    social_links:
        facebook: https://www.facebook.com/AndrewChen.good
        google: mailto:chenpoanandrew@gmail.com
        github: https://github.com/PolarBearAndrew
        linkedin: https://www.linkedin.com/in/andrewchenonlinked/?locale=zh_TW
        briefcase: https://www.cakeresume.com/db77c1
        # twitter: https://twitter.com/?lang=zh-tw
        # rss: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false


# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: UA-65872031-1 # enter the tracking ID for your Google Analytics
    google_site_verification: 1.0 # enter Google site verification code
    # baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        # JSDC: http://jsdc.tw
        # Hackathon Taiwan: https://hackathon.tw
        Hexo: http://hexo.io
        Hexo-theme Icarus: https://github.com/ppoffice/hexo-theme-icarus
